import { useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Popup, CircleMarker } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

// Fix for default Leaflet icons in React
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',
  iconUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',
  shadowUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',
});

// Mock hotspot data generated by AI clustering
const hotspots = [
  { id: 1, pos: [12.9716, 77.5946], category: 'Roads', intensity: 8, requests: 214, desc: 'Potholes near XYZ School' },
  { id: 2, pos: [12.9650, 77.5850], category: 'Water', intensity: 5, requests: 80, desc: 'Water logging' },
  { id: 3, pos: [12.9800, 77.6000], category: 'Health', intensity: 9, requests: 310, desc: 'No medicines in PHC' },
];

const getCategoryColor = (category) => {
  switch (category) {
    case 'Roads': return '#3b82f6'; // blue-500
    case 'Water': return '#06b6d4'; // cyan-500
    case 'Health': return '#ef4444'; // red-500
    default: return '#8b5cf6'; // violet-500
  }
};

export default function MapComponent() {
  // Center map on a mock constituency (e.g., Bangalore)
  const position = [12.9716, 77.5946];

  return (
    <div className="h-full w-full rounded-2xl overflow-hidden border border-white/10 relative z-0">
      <MapContainer center={position} zoom={13} style={{ height: '100%', width: '100%' }}>
        {/* Using a premium dark-themed tile layer (CartoDB Dark Matter) */}
        <TileLayer
          url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
        />
        
        {hotspots.map((spot) => (
          <CircleMarker
            key={spot.id}
            center={spot.pos}
            radius={spot.intensity * 3} // Size based on intensity
            pathOptions={{
              color: getCategoryColor(spot.category),
              fillColor: getCategoryColor(spot.category),
              fillOpacity: 0.5,
              weight: 2
            }}
          >
            <Popup className="custom-popup">
              <div className="p-1">
                <div className="font-bold text-gray-900">{spot.category} Issue</div>
                <div className="text-sm text-gray-700">{spot.desc}</div>
                <div className="mt-2 inline-block px-2 py-1 bg-red-100 text-red-700 text-xs font-bold rounded">
                  {spot.requests} Requests
                </div>
              </div>
            </Popup>
          </CircleMarker>
        ))}
      </MapContainer>
    </div>
  );
}
